services:
  - type: web
    name: zapato_app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn zapato.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
        name: zapato_db
        property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key : WEB_CONCURRENCY
        value: 4
    plan: free
    autoDeploy: true

  - type: postgres
    name: zapato_db
    plan: free
    region: oregon
    databaseName: zapato_db
    user: administrador
    password: A12345*/.